[build]
  command   = "npm install && npm install --prefix functions//graphql && prisma2 generate --schema=functions/graphql/prisma/schema.prisma && npm run build"
  functions = "functions"
  publish   = "public"